#docker-compose.ymlのバージョン
version: '3'

#フロント
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
      # CHOKIDAR_USEPOLLING: true
    volumes:
      - ./:/src
      # - node_modules:/src/node_modules
    tty: true